[package]
name = "client"
version = "0.0.0"
edition = "2024"

[dependencies]
async-tungstenite = { version = "0.29.1", features = ["tokio-rustls-webpki-roots", "tokio"] }
futures = "0.3.31"
iced = { git = "https://github.com/iced-rs/iced.git", branch = "master", features = ["image", "advanced", "sipper", "tokio", "svg"] }
tokio = { version = "1.45.1", features = ["fs", "time"] }
iced_split = { git = "https://github.com/edwloef/iced_split.git", branch = "main" }
dragking = { git = "https://github.com/airstrike/dragking.git", branch = "dev/master" }
iced_dialog = { git = "https://github.com/pml68/iced_dialog.git", branch = "master" }
uuid = { version = "1.17.0", features = ["serde", "v4"] }
reqwest = "0.12.20"
tracing = {  version = "0.1.41" }
tracing-subscriber = "0.3.19"
protocol = { path = "../protocol" }
serde_json = "1.0.140"
