[server]
host = [0, 0, 0, 0]
port = 3000

[info]
server_name = "The Guild"
icon = "server_icon.svg"
channels = [
  "General",
  "Gaming",
  "Coding Den"
]

[database]
addr = "postgres://jprugel:13875j_P@postgres:5432/database"
