on: push
name: cargo_fmt
env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  cargo_clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: run_cargo_fmt
        run: cargo fmt -- --check
